version: "3"

services:

  mariadb:
    image: mariadb:11.1.2-jammy
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  mariadb-data:
